# Generated by Django 3.1.6 on 2021-02-14 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=500, unique=True, verbose_name='Name of the Anime')),
                ('url', models.URLField(blank=True, help_text='Optional', null=True, verbose_name='Anime Description Url')),
            ],
            options={
                'verbose_name_plural': 'Anime Name',
            },
        ),
        migrations.CreateModel(
            name='AnimeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Anime Image Url')),
                ('anime_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmain.animename', verbose_name='Anime Category')),
            ],
            options={
                'verbose_name_plural': 'Anime Image',
            },
        ),
    ]
