# Generated by Django 3.1.3 on 2020-11-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servername', models.CharField(max_length=500, null=True, verbose_name='Server Name')),
                ('server_user_data', models.JSONField(default=dict, verbose_name='Server Users Data')),
            ],
        ),
    ]
