# Generated by Django 3.1.6 on 2021-02-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeimage',
            name='image',
            field=models.URLField(unique=True, verbose_name='Anime Image Url'),
        ),
    ]
