# Generated by Django 3.1.6 on 2021-02-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0002_auto_20210215_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(verbose_name='Website Url Field')),
                ('widget', models.TextField(blank=True, help_text='Optional', null=True, verbose_name='Website Bot Widget Code')),
            ],
            options={
                'verbose_name_plural': 'Discord Bot List Websites',
            },
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(verbose_name='Website Url Field')),
            ],
            options={
                'verbose_name_plural': 'Server List Websites',
            },
        ),
    ]
