# Generated by Django 3.1.6 on 2021-02-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0003_discordbotlist_serverlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True)),
                ('weebhook_id', models.TextField(unique=True)),
                ('webhook_token', models.TextField(unique=True)),
            ],
        ),
    ]
