# Generated by Django 3.1.6 on 2021-02-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botmain', '0004_webhook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webhook',
            new_name='Webhooks',
        ),
        migrations.AlterModelOptions(
            name='webhooks',
            options={'verbose_name_plural': 'Webhooks'},
        ),
    ]
