from .badges import *
from .developer import *
from .img import *
from .music import *
from .polls import *
from .reaction_roles import *
from .reminder import *
from .shinobi_match import *
from .weather import *
from .moderation import *
from .info import *
from .fun import *
from .events import *
from .anime_and_vocaloids import *