documentation:
  - README.md
  
wontfix: 
  -any: [CONTRIBUTING.md, CODE_OF_CONDUCT.md, LICENSE]

dependencies: 
  -any: [requirements]

help wanted: 
  -any: ['minato_namikaze/bot_files/*']

bug: 
  -any: [discordbot.py]
