version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "requirements.min.txt",
  "requirements.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 250
  type_checker = "mypy"
  skip_doc_coverage = ["module", "magic", "init"]
  additional_builtins = ["_", "pretty_output"]

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "yapf"
enabled = true
