"""first init

Revision ID: c685b2a5fd53
Revises:
Create Date: 2024-03-28 08:27:01.495168

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c685b2a5fd53"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "badges",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("badge_name", sa.String(length=250), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("is_inverted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_badges_badge_name"), "badges", ["badge_name"], unique=True)
    op.create_index(op.f("ix_badges_code"), "badges", ["code"], unique=True)
    op.create_index(op.f("ix_badges_file_name"), "badges", ["file_name"], unique=True)
    op.create_index(op.f("ix_badges_id"), "badges", ["id"], unique=False)
    op.create_index(
        op.f("ix_badges_is_inverted"),
        "badges",
        ["is_inverted"],
        unique=True,
    )
    op.create_table(
        "reaction_roles",
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("reactions", sa.JSON(), nullable=False),
        sa.Column("limit_to_one", sa.Boolean(), nullable=False),
        sa.Column(
            "custom_id",
            sa.ARRAY(sa.String(length=250), as_tuple=True, zero_indexes=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index(
        op.f("ix_reaction_roles_channel_id"),
        "reaction_roles",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reaction_roles_custom_id"),
        "reaction_roles",
        ["custom_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reaction_roles_limit_to_one"),
        "reaction_roles",
        ["limit_to_one"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reaction_roles_message_id"),
        "reaction_roles",
        ["message_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_reaction_roles_server_id"),
        "reaction_roles",
        ["server_id"],
        unique=False,
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reminders_expires"),
        "reminders",
        ["expires"],
        unique=False,
    )
    op.create_index(op.f("ix_reminders_id"), "reminders", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminders_id"), table_name="reminders")
    op.drop_index(op.f("ix_reminders_expires"), table_name="reminders")
    op.drop_table("reminders")
    op.drop_index(op.f("ix_reaction_roles_server_id"), table_name="reaction_roles")
    op.drop_index(op.f("ix_reaction_roles_message_id"), table_name="reaction_roles")
    op.drop_index(op.f("ix_reaction_roles_limit_to_one"), table_name="reaction_roles")
    op.drop_index(op.f("ix_reaction_roles_custom_id"), table_name="reaction_roles")
    op.drop_index(op.f("ix_reaction_roles_channel_id"), table_name="reaction_roles")
    op.drop_table("reaction_roles")
    op.drop_index(op.f("ix_badges_is_inverted"), table_name="badges")
    op.drop_index(op.f("ix_badges_id"), table_name="badges")
    op.drop_index(op.f("ix_badges_file_name"), table_name="badges")
    op.drop_index(op.f("ix_badges_code"), table_name="badges")
    op.drop_index(op.f("ix_badges_badge_name"), table_name="badges")
    op.drop_table("badges")
    # ### end Alembic commands ###
