"""badges

Revision ID: d80905354d9d
Revises: f887ee30444e
Create Date: 2022-06-28 12:37:08.506648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80905354d9d'
down_revision = 'f887ee30444e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('badge_name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('is_inverted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_badge_name'), 'badges', ['badge_name'], unique=True)
    op.create_index(op.f('ix_badges_code'), 'badges', ['code'], unique=True)
    op.create_index(op.f('ix_badges_file_name'), 'badges', ['file_name'], unique=True)
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_index(op.f('ix_badges_is_inverted'), 'badges', ['is_inverted'], unique=True)
    op.create_index(op.f('ix_premium_configurable_prefix'), 'premium', ['configurable_prefix'], unique=False)
    op.create_index(op.f('ix_premium_id'), 'premium', ['id'], unique=False)
    op.create_index(op.f('ix_premium_name'), 'premium', ['name'], unique=False)
    op.create_index(op.f('ix_premium_no_of_servers_applicable'), 'premium', ['no_of_servers_applicable'], unique=False)
    op.create_index(op.f('ix_premium_no_vote_locked'), 'premium', ['no_vote_locked'], unique=False)
    op.create_index(op.f('ix_premium_reaction_roles_amount'), 'premium', ['reaction_roles_amount'], unique=False)
    op.create_index(op.f('ix_premium_reminder_amount_per_user'), 'premium', ['reminder_amount_per_user'], unique=False)
    op.create_index(op.f('ix_premium_reminders_amount'), 'premium', ['reminders_amount'], unique=False)
    op.create_index(op.f('ix_server_blacklisted'), 'server', ['blacklisted'], unique=False)
    op.create_index(op.f('ix_server_id'), 'server', ['id'], unique=False)
    op.create_index(op.f('ix_server_prefix'), 'server', ['prefix'], unique=False)
    op.create_index(op.f('ix_server_premium_applier_user_id'), 'server', ['premium_applier_user_id'], unique=False)
    op.create_index(op.f('ix_server_show_404_commands_error'), 'server', ['show_404_commands_error'], unique=False)
    op.create_index(op.f('ix_user_blacklisted'), 'user', ['blacklisted'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_premium_expiry'), 'user', ['premium_expiry'], unique=False)
    op.create_index(op.f('ix_user_premium_id'), 'user', ['premium_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_premium_id'), table_name='user')
    op.drop_index(op.f('ix_user_premium_expiry'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_blacklisted'), table_name='user')
    op.drop_index(op.f('ix_server_show_404_commands_error'), table_name='server')
    op.drop_index(op.f('ix_server_premium_applier_user_id'), table_name='server')
    op.drop_index(op.f('ix_server_prefix'), table_name='server')
    op.drop_index(op.f('ix_server_id'), table_name='server')
    op.drop_index(op.f('ix_server_blacklisted'), table_name='server')
    op.drop_index(op.f('ix_premium_reminders_amount'), table_name='premium')
    op.drop_index(op.f('ix_premium_reminder_amount_per_user'), table_name='premium')
    op.drop_index(op.f('ix_premium_reaction_roles_amount'), table_name='premium')
    op.drop_index(op.f('ix_premium_no_vote_locked'), table_name='premium')
    op.drop_index(op.f('ix_premium_no_of_servers_applicable'), table_name='premium')
    op.drop_index(op.f('ix_premium_name'), table_name='premium')
    op.drop_index(op.f('ix_premium_id'), table_name='premium')
    op.drop_index(op.f('ix_premium_configurable_prefix'), table_name='premium')
    op.drop_index(op.f('ix_badges_is_inverted'), table_name='badges')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_file_name'), table_name='badges')
    op.drop_index(op.f('ix_badges_code'), table_name='badges')
    op.drop_index(op.f('ix_badges_badge_name'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###