name: lint

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.x' ]

    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip setuptools wheel black requests pipenv
          pipenv requirements > requirements.txt
          python -m pip install -U -r  requirements.txt

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run black
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
          black --check minato_namikaze launcher.py
